/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Domain.Car;
import File.CarFile;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author rivai
 */
public class AddCar extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddCar
     */
    public static CarFile carFile;
    public AddCar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtName = new javax.swing.JTextField();
        LbName = new javax.swing.JLabel();
        LbYear = new javax.swing.JLabel();
        TxtYear = new javax.swing.JTextField();
        LbMileage = new javax.swing.JLabel();
        TxtMileage = new javax.swing.JTextField();
        LbAmerican = new javax.swing.JLabel();
        BttSave = new javax.swing.JButton();
        BttOut = new javax.swing.JButton();
        TxtAmerican = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TxtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNameActionPerformed(evt);
            }
        });

        LbName.setText("Nombre");

        LbYear.setText("Año");

        TxtYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtYearActionPerformed(evt);
            }
        });

        LbMileage.setText("Kilometraje");

        LbAmerican.setText("Americano (si/no)");

        BttSave.setText("Guardar");
        BttSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttSaveActionPerformed(evt);
            }
        });

        BttOut.setText("Salir");
        BttOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LbAmerican)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtName)
                            .addComponent(TxtYear)
                            .addComponent(TxtMileage)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LbName)
                                    .addComponent(LbYear)
                                    .addComponent(LbMileage))
                                .addGap(0, 220, Short.MAX_VALUE))
                            .addComponent(TxtAmerican))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(BttSave)
                .addGap(28, 28, 28)
                .addComponent(BttOut)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LbName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LbYear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LbMileage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtMileage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LbAmerican)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtAmerican, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BttSave)
                    .addComponent(BttOut))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TxtNameActionPerformed

    private void TxtYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtYearActionPerformed

    private void BttSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttSaveActionPerformed
        // TODO add your handling code here:
        Car car= new Car();
        car.setName(TxtName.getText());
        car.setYear(Integer.parseInt(TxtYear.getText()));
        car.setMileage(Float.parseFloat(TxtMileage.getText()));
        if(TxtAmerican.getText().equalsIgnoreCase("si")||TxtAmerican.getText().equalsIgnoreCase("sí")){
            car.setAmerican(true);
            try {
                carFile.putValue(car);
            } catch (IOException e) {
                System.out.println(e);
            }
        }else{
            if(TxtAmerican.getText().equalsIgnoreCase("no")){
                car.setAmerican(false);
            }else{
                JOptionPane.showMessageDialog(null,"American data is invalid");
            }
        }
    }//GEN-LAST:event_BttSaveActionPerformed

    private void BttOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttOutActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BttOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BttOut;
    private javax.swing.JButton BttSave;
    private javax.swing.JLabel LbAmerican;
    private javax.swing.JLabel LbMileage;
    private javax.swing.JLabel LbName;
    private javax.swing.JLabel LbYear;
    private javax.swing.JTextField TxtAmerican;
    private javax.swing.JTextField TxtMileage;
    private javax.swing.JTextField TxtName;
    private javax.swing.JTextField TxtYear;
    // End of variables declaration//GEN-END:variables
}
