/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Domain.Car;
import File.CarFile;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author rivai
 */
public class Update extends javax.swing.JInternalFrame {

    /**
     * Creates new form Update
     */
    public static CarFile carFile;
    public Update() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbSerie = new javax.swing.JLabel();
        TxtSerie = new javax.swing.JTextField();
        LbName = new javax.swing.JLabel();
        LbYear = new javax.swing.JLabel();
        LbAmerican = new javax.swing.JLabel();
        TxtName = new javax.swing.JTextField();
        TxtYear = new javax.swing.JTextField();
        TxtAmerican = new javax.swing.JTextField();
        BttUpdate = new javax.swing.JButton();
        BttCancel = new javax.swing.JButton();
        BttSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TxtMileage = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LbSerie.setText("Serie");

        LbName.setText("Nombre");

        LbYear.setText("Año");

        LbAmerican.setText("Americano");

        BttUpdate.setText("Actualizar");
        BttUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttUpdateActionPerformed(evt);
            }
        });

        BttCancel.setText("Cancelar");

        BttSearch.setText("Buscar");
        BttSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttSearchActionPerformed(evt);
            }
        });

        jLabel1.setText("Kilometraje");

        TxtMileage.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtSerie)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LbName)
                                    .addComponent(LbSerie)
                                    .addComponent(TxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(97, 97, 97)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LbYear)
                                    .addComponent(TxtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(TxtMileage, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtAmerican, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LbAmerican)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(184, 184, 184)
                                .addComponent(BttUpdate)
                                .addGap(164, 164, 164)
                                .addComponent(BttCancel))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(BttSearch)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LbSerie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BttSearch)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbName)
                    .addComponent(LbYear)
                    .addComponent(LbAmerican)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtAmerican, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtMileage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BttUpdate)
                    .addComponent(BttCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BttSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttSearchActionPerformed
        Car car=new Car();
        try {
            // TODO add your handling code here:
            car=carFile.getCar(Integer.parseInt(TxtSerie.getText()));
        } catch (IOException e) {
            System.out.println(e);
        }
        TxtName.setText(car.getName());
        TxtYear.setText(String.valueOf(car.getYear()));
        TxtMileage.setText(String.valueOf(car.getMileage()));
        if(car.isAmerican()){
            TxtAmerican.setText("Si");
        }else{
            TxtAmerican.setText("No");
        }
    }//GEN-LAST:event_BttSearchActionPerformed

    private void BttUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttUpdateActionPerformed
        // TODO add your handling code here:
        Car car2=new Car();
        car2.setName(TxtName.getText());
        car2.setYear(Integer.parseInt(TxtYear.getText()));
        car2.setMileage(Float.parseFloat(TxtMileage.getText()));
        if(TxtAmerican.getText().equalsIgnoreCase("si")||TxtAmerican.getText().equalsIgnoreCase("sí")){
            car2.setAmerican(true);
        }else{
            car2.setAmerican(false);
        }
        try {
            carFile.updateValue(Integer.parseInt(TxtSerie.getText()),car2);
        } catch (IOException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_BttUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BttCancel;
    private javax.swing.JButton BttSearch;
    private javax.swing.JButton BttUpdate;
    private javax.swing.JLabel LbAmerican;
    private javax.swing.JLabel LbName;
    private javax.swing.JLabel LbSerie;
    private javax.swing.JLabel LbYear;
    private javax.swing.JTextField TxtAmerican;
    private javax.swing.JTextField TxtMileage;
    private javax.swing.JTextField TxtName;
    private javax.swing.JTextField TxtSerie;
    private javax.swing.JTextField TxtYear;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
